### PR TITLE
Add escalations - rsync fix - Host/Hostgroup Excludes in Advanced Services

### PR DESCRIPTION
**Pull request by irstmon**
Add escalations for hosts / services / advanced services
Fix rsync
Add excludes for advanced services
Service escalations can only select one host, if services are added that are not found in the host config the specific service escalation is ignored (only the services that could not be found)
Add Event-Handler to nconf

### CODE REVIEW

**Comment by Cat5TV** [comment]
Thanks @irstmon -- after all this time of maintaining a current nConf virtually alone, it's nice to receive a PR.  :)  I will review this over the next few days. Just in the middle of NEMS 1.5's development cycle (it releases next month) so hopefully can squeeze this in and it will be merged into the NEMS 1.5 release if there aren't any issues.

Thanks again!

**Comment by irstmon** [comment]
I'm the author of the linked nconf thread about the escalations, so I've added it a while back and have been happy with it until the PHP7 problem - that's when I stumbled upon this. Since I've really NO idea about perl my fixes/addons might not be exactly pretty, but they work ;-) It's a bit try/error until it works the way it should. I've yet to add the Event Handler setting, hope on adding it tomorrow (it's just a little SQL line so it shouldn't be mutch, but I can't find it right now :-) )

**Comment by Cat5TV** [comment]
This is fine for fresh installs, but will be a challenge to merge to NEMS servers. Would you be able to provide more information about the changes made to the database tables so we can write an update script to modify existing tables (rather than inserting new ones)?

**Comment by irstmon** [comment]
The only tricky part in the databases are the ones in ConfigClasses - the ids must match the added entries in ConfigAttrs. The ids in ConfigAttrs could be NULL instead of 200-something for the added things - this way the SQL server selects the next free number.

So as long as there are no added Classes in existing installations there shouldn't be a problem. If you allready added classes than the numbers 19-22 need to be changed in ConfigAttrs (since this is the way they are reffered to).

Hope you understand what I want to say, since I'm not a native speaker it might be a bit hard ;-)

**Comment by Cat5TV** [comment]
@irstmon are you still interested in seeing this merged? I will be doing some heavy work on NConf in the next while and would love to integrate this, but I'd like to know you are available to assist if needed.

Thanks.

**Comment by irstmon** [comment]
@Cat5TV Sorry for the delay - this got burried. Happy to see it merged! If there are any problems feel free to reach out!

**Comment by Cat5TV** [comment]
@irstmon yes; please email me nems@category5.tv or better yet, join our Discord and ping me. https://discord.gg/e9xT9mh

**Pull request merged**
